import type { ThemeConfig } from 'antd';
import { theme } from 'antd';

// Stadium palette — midnight navy + champagne gold
export const smartgroupTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary: '#D4A93C',
    colorLink:    '#7BA7E8',
    colorSuccess: '#5DBF8A',
    colorWarning: '#E8B85A',
    colorError:   '#E26A5E',
    fontFamily: "'Plus Jakarta Sans', 'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    fontFamilyCode: "'JetBrains Mono', monospace",
    fontSize: 14,
    colorBgLayout:    '#0A0D14',
    colorBgContainer: '#0F1320',
    colorBgElevated:  '#141A2A',
    colorBgSpotlight: '#1A2236',
    colorBorder:          '#232B40',
    colorBorderSecondary: '#2D3550',
    colorText:          '#F1F2EE',
    colorTextSecondary: '#B8BCC4',
    colorTextTertiary:  '#7A7F8A',
    borderRadius: 10,
    borderRadiusLG: 14,
    borderRadiusSM: 6,
    wireframe: false,
  },
  components: {
    Button: {
      colorPrimary: '#D4A93C',
      colorPrimaryHover: '#E5BC4F',
      primaryColor: '#0A0D14',
      controlHeight: 36,
      fontWeight: 600,
    },
    Menu: {
      darkItemBg:             '#0F1320',
      darkItemSelectedBg:     'rgba(212, 169, 60, 0.12)',
      darkItemSelectedColor:  '#E5BC4F',
      darkItemColor:          '#B8BCC4',
      darkItemHoverColor:     '#F1F2EE',
      darkItemHoverBg:        '#141A2A',
      itemBorderRadius:       10,
      itemMarginInline:       8,
    },
    Card: {
      colorBgContainer:     '#0F1320',
      colorBorderSecondary: '#232B40',
      borderRadiusLG:       14,
    },
    Table: {
      colorBgContainer: '#0F1320',
      headerBg:         '#141A2A',
      rowHoverBg:       '#1A2236',
      borderColor:      '#232B40',
      headerColor:      '#7A7F8A',
    },
    Input: {
      colorBgContainer:  '#141A2A',
      colorBorder:       '#232B40',
      activeBorderColor: '#D4A93C',
      hoverBorderColor:  '#2D3550',
    },
    InputNumber: {
      colorBgContainer:  '#141A2A',
      colorBorder:       '#232B40',
      activeBorderColor: '#D4A93C',
      controlHeight:     40,
    },
    Select: {
      colorBgContainer:    '#141A2A',
      colorBorder:         '#232B40',
      optionSelectedBg:    'rgba(212, 169, 60, 0.12)',
      optionSelectedColor: '#E5BC4F',
    },
    Tag: { defaultBg: '#141A2A', defaultColor: '#B8BCC4' },
    Progress: { defaultColor: '#D4A93C', remainingColor: '#232B40' },
    Tabs: {
      itemActiveColor:   '#E5BC4F',
      itemSelectedColor: '#E5BC4F',
      itemHoverColor:    '#F1F2EE',
      inkBarColor:       '#D4A93C',
    },
    Alert: {
      colorWarningBg:     'rgba(232, 184, 90, 0.10)',
      colorWarningBorder: 'rgba(232, 184, 90, 0.30)',
      colorInfoBg:        'rgba(123, 167, 232, 0.10)',
      colorInfoBorder:    'rgba(123, 167, 232, 0.30)',
    },
    Statistic: { titleFontSize: 12, contentFontSize: 28 },
    Descriptions: { colorSplit: '#232B40', labelBg: '#141A2A' },
  },
};
